### ISSUE TITLE
Como podemos melhorar esse jogo?

### ISSUE THREAD

**Issue by emmanuelXavier** [emmanuelXavier/jogohtml5#1]
Essa issue foi criada para abertura da discussão sobre as melhorias que iremos efetuar durante a disciplina de Laboratório de Programação Web do 4 período da Facimp.

Favor insiram suas sugestões de melhoria.

**Comment by p9matheus** [comment]
Seria uma boa a criação de níveis de dificuldade. Quanto maior o nível mais rápido a bola irá se movimentar. O usuário escolheria a dificuldade em que desejaria iniciar o jogo. Fica aqui mais uma questão, se o usuário escolhe uma determinada dificuldade a bola continuará aumentando de velocidade com o tempo? (Assim o nível seria apenas para iniciar, visto que o mesmo aumentará com o decorrer do tempo) Ou será uma velocidade fixa? Minha opinião é de que seja a velocidade fixa.

**Comment by WelderRodrigues** [comment]
E se colocasse um total de vidas ou chances de jogar novamente, por exemplo, 5 vidas inicias e de acordo com os pontos conseguidos no jogo fossem conquistando mais vidas assim aumentando o nível da dificuldade até acabar as vidas e o jogo chegar ao fim. Game over.

**Comment by emmanuelXavier** [comment]
Gostei muito @paul0matheus  e concordo com sua opinião.

**Comment by emmanuelXavier** [comment]
Show de bola @WelderRodrigues ótima idéia.

**Comment by iosley** [comment]
Seria interessante se pudesse mudar a direção da bola quando ela bater no canto da barra ou quando a barra se movimenta em sentido contrario a direção da bola durante o toque.

**Comment by ThallesCanela** [comment]
Poderíamos avançar os níveis conforme a quantidade de acertos do jogador.

**Comment by joaodosdados** [comment]
Adição do Modo Custom: mapas com obstáculos(blocos dispostos na tela),ou um modo campanha com vários mapas que de acordo com a quantidade de pontos os mapas mudariam e os obstáculos ficariam mais difíceis.

**Comment by emmanuelXavier** [comment]
Show @iosley, @ThallesCanela , @lucasxms

**Comment by bismarcksi** [comment]
Sobre a mudança de nível do game,
Aumentar a dificuldade do game de acordo com a quantidade de vezes que a bolinha atinge a barra.
Ex: A bolinha atinge a barra 20 vezes, automaticamente mudar do nível fácil para o nível normal, ou do nível normal para o nivel hard, E em seguida apresentar uma mensagem na tela indicando que mudou a dificuldade do game e em qual dificuldade o game se encontra.
